### ISSUE TITLE
slippage

### ISSUE THREAD

**Issue by cryptochonkz** [vincor1986/merlin#1]
Seems to work, ive modified it to fit polygon although getting lots of "Fail with error 'UniswapV2Router: INSUFFICIENT_OUTPUT_AMOUNT" errors. guessing this might be due to slippage. any idea where to adjust slippage?

**Comment by vincor1986** [comment]
"INSUFFICIENT_OUTPUT_AMOUNT" errors are very common with merlin, even during periods of profitibility.

The PancakeSwap V2 contract function (swapExactTokensForTokens) accepts an 'amountOutMin' parameter. The value passed as this parameter on execution is the 'minOutput' property value from config.js, which is calculated by summing the 'inputAmount' and 'tradeCost' properties from same file.

So the "INSUFFICIENT_OUTPUT_AMOUNT" error is returned when the output amount calculated by the PancakeSwap router during tx is less than the value specified by 'minOutput', i.e. the tx was reverted.

The 'minOutput' is balanced to trigger that response if the tx sender would end up with a larger loss than the cost of the tx reverting.  

During times of volatile bullishness / bearishness - merlin has executed far more successful transactions than in flatter markets. Even during those extreme market conditions, merlin still has lots of "INSUFFICIENT_OUTPUT_AMOUNT" failed transactions (sometimes 100 in a day) - but nonetheless executed enough successful trades around those to make an overall and at times significant profit.

I hope that helps, let me know if you have any suggestions for improvements or would like any more information.

**Comment by ifunanya55** [comment]
> "INSUFFICIENT_OUTPUT_AMOUNT" errors are very common with merlin, even during periods of profitibility.
> 
> The PancakeSwap V2 contract function (swapExactTokensForTokens) accepts an 'amountOutMin' parameter. The value passed as this parameter on execution is the 'minOutput' property value from config.js, which is calculated by summing the 'inputAmount' and 'tradeCost' properties from same file.
> 
> So the "INSUFFICIENT_OUTPUT_AMOUNT" error is returned when the output amount calculated by the PancakeSwap router during tx is less than the value specified by 'minOutput', i.e. the tx was reverted.
> 
> The 'minOutput' is balanced to trigger that response if the tx sender would end up with a larger loss than the cost of the tx reverting.
> 
> During times of volatile bullishness / bearishness - merlin has executed far more successful transactions than in flatter markets. Even during those extreme market conditions, merlin still has lots of "INSUFFICIENT_OUTPUT_AMOUNT" failed transactions (sometimes 100 in a day) - but nonetheless executed enough successful trades around those to make an overall and at times significant profit.
> 
> I hope that helps, let me know if you have any suggestions for improvements or would like any more information.

so does it mean we can't set slippage ? 

i am also having lots of insufficient output amount :(

**Comment by vincor1986** [comment]
Hi ifunanya55, I've responded to your question in issue #2, please let me know if you need any more info there.
