### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by omototan** [vincor1986/merlin#3]
Is there any channel to get in touch with other currently using this tool? Like a Telegram or something? I think this would be interesting so we can share successful strategies.

**Comment by vincor1986** [comment]
My apologies for the delay in getting back to you.

I didn't establish such a group for a couple of reasons. I just felt being that different users of Merlin would be in competition with each other, it was unlikely that anyone who did experience positive results would share their strategies. Also, I feel unable to moderate such a group. 

If you did want to start a channel, I'd be happy to put a link in the readme just in case like-minded users want to contribute.
